spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/interview_challenge?user=admin&password=admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect