CREATE TABLE IF NOT EXISTS financial_statements(
    id UUID NOT NULL,
    person_id VARCHAR(250) NOT NULL UNIQUE,
    rating VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_financial_statement PRIMARY KEY (id)
)